// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"wire_test/pkg/auth/internal"
	"wire_test/pkg/filesystem"
	"wire_test/pkg/storage"
)

// Injectors from wire.go:

func InitializeSmtpClient(address internal.SmtpAddress) (*internal.SmtpClient, error) {
	smtpClient, err := internal.NewSmtpClient(address)
	if err != nil {
		return nil, err
	}
	return smtpClient, nil
}

func InitializeAuthenticator(address internal.SmtpAddress, appDataRoot filesystem.PathString) (*Authenticator, error) {
	smtpClient, err := InitializeSmtpClient(address)
	if err != nil {
		return nil, err
	}
	fileSystem, err := filesystem.NewFileSystem(appDataRoot)
	if err != nil {
		return nil, err
	}
	authRepository := storage.NewAuthRepository(fileSystem)
	authenticator := NewAuthenticator(smtpClient, authRepository)
	return authenticator, nil
}
